apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: titanic-db-pvc
  namespace: titanic-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3  # AWS EBS storage class
